/**
 * A deliberately tiny markdown subset (Phase 63.3).
 *
 * The morning briefing is generated by us (lib/briefing), so the syntax
 * in play is known and small: h2/h3, **bold**, `code`, and - / 1. lists.
 * Parsing to an AST — rather than to an HTML string — means nothing is
 * ever handed to dangerouslySetInnerHTML, so briefing content (which can
 * quote project names, paths and log lines) can never inject markup.
 */

export type Inline =
  | { type: "text"; value: string }
  | { type: "strong"; value: string }
  | { type: "code"; value: string };

export type Block =
  | { type: "heading"; level: 2 | 3; children: Inline[] }
  | { type: "paragraph"; children: Inline[] }
  | { type: "list"; ordered: boolean; items: Inline[][] };

const HEADING = /^(#{2,3})\s+(.*)$/;
const BULLET = /^\s*[-*]\s+(.*)$/;
const NUMBERED = /^\s*\d+[.)]\s+(.*)$/;

/** Split a line into text / **strong** / `code` runs. */
function parseInline(line: string): Inline[] {
  const out: Inline[] = [];
  const re = /\*\*(.+?)\*\*|`([^`]+)`/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(line)) !== null) {
    if (m.index > last) {
      out.push({ type: "text", value: line.slice(last, m.index) });
    }
    if (m[1] !== undefined) out.push({ type: "strong", value: m[1] });
    else out.push({ type: "code", value: m[2] });
    last = m.index + m[0].length;
  }
  if (last < line.length) out.push({ type: "text", value: line.slice(last) });
  return out.length > 0 ? out : [{ type: "text", value: line }];
}

export function parseMarkdownLite(src: string): Block[] {
  const blocks: Block[] = [];
  const lines = src.split("\n");

  let paragraph: string[] = [];
  let list: { ordered: boolean; items: Inline[][] } | null = null;

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    blocks.push({ type: "paragraph", children: parseInline(paragraph.join(" ")) });
    paragraph = [];
  };
  const flushList = () => {
    if (!list) return;
    blocks.push({ type: "list", ordered: list.ordered, items: list.items });
    list = null;
  };
  const flushAll = () => {
    flushParagraph();
    flushList();
  };

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (line.trim() === "") {
      flushAll();
      continue;
    }

    const heading = line.match(HEADING);
    if (heading) {
      flushAll();
      blocks.push({
        type: "heading",
        level: heading[1].length === 2 ? 2 : 3,
        children: parseInline(heading[2].trim()),
      });
      continue;
    }

    const bullet = line.match(BULLET);
    const numbered = !bullet ? line.match(NUMBERED) : null;
    if (bullet || numbered) {
      flushParagraph();
      const ordered = !!numbered;
      // A change of list type starts a new list.
      if (list && list.ordered !== ordered) flushList();
      if (!list) list = { ordered, items: [] };
      list.items.push(parseInline((bullet ? bullet[1] : numbered![1]).trim()));
      continue;
    }

    flushList();
    paragraph.push(line.trim());
  }

  flushAll();
  return blocks;
}
